# Generated by Django 2.2.1 on 2019-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('att_name', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
