# Generated by Django 2.2.1 on 2019-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190506_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
