# Generated by Django 2.2.1 on 2019-05-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_sweets_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweets',
            name='img',
        ),
    ]
