# Generated by Django 2.2.1 on 2019-05-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_sweets_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_Name', models.CharField(max_length=120)),
                ('Carbohydrate', models.IntegerField()),
                ('Protein', models.IntegerField()),
                ('Calories', models.IntegerField()),
                ('Fat', models.IntegerField()),
            ],
        ),
    ]
