# Generated by Django 2.2.1 on 2019-05-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_add_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('swet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Sweets')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_Dish',
        ),
    ]
