# Generated by Django 2.2.1 on 2019-05-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190529_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='swet',
        ),
    ]
